name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Define the branch to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Action to checkout your repository

      - name: Set up PHP
        uses: shivammathur/setup-php@v2  # Action to set up PHP environment
        with:
          php-version: '8.3'  # Specify the PHP version you need

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader  # Install PHP dependencies using Composer

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit  # Execute PHPUnit tests, adjust path if necessary

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.207.249.244 'cd /var/www/html && git pull origin main'  # Example deployment script using SSH

      - name: Notify deployment success
        if: success()
        run: echo "Deployment to AWS EC2 succeeded!"

      - name: Notify deployment failure
        if: failure()
        run: echo "Deployment to AWS EC2 failed."

